"""Algorithm-layer implementations for SIAC."""

from siac.algorithms.brdf import BRDFKernels, compute_reflectance
from siac.algorithms.correction import AtmosphericCorrector, CorrectionResult
from siac.algorithms.grid import assemble_grids
from siac.algorithms.solver import (
    CostFunction,
    CostFunctionConfig,
    MultiGridConfig,
    MultiGridSolver,
    SolverResult,
    apply_smoothness_filter,
    compute_laplacian_eigenvalues,
    create_sparse_laplacian,
    solve_atmospheric_parameters,
)
from siac.algorithms.surface import (
    BRDFWhittakerDeriver,
    HyperspectralLibrary,
    KernelModelDeriver,
    MonthlyBestPixelComposite,
    MonthlyCompositeCollection,
    MonthlyCompositeDatabase,
    MonthlyKernelWeightComposite,
    PSFConvolver,
    SpectralMapper,
    SpectralMappingConfig,
    build_monthly_best_pixel_composite,
    build_monthly_best_pixel_kernel_composite,
    build_monthly_composite_database,
    build_monthly_composites_from_brdf,
    build_monthly_surface_prior_database,
    convolve_hyperspectral_reflectance,
    generate_monthly_composites_from_brdf,
    map_multispectral_reflectance,
    needs_spectral_mapping,
    query_surface_prior_from_monthly_database,
    resample_geometry_for_surface_prior,
)

__all__ = [
    "AtmosphericCorrector",
    "CorrectionResult",
    "assemble_grids",
    "CostFunction",
    "CostFunctionConfig",
    "compute_laplacian_eigenvalues",
    "apply_smoothness_filter",
    "create_sparse_laplacian",
    "MultiGridSolver",
    "MultiGridConfig",
    "SolverResult",
    "solve_atmospheric_parameters",
    "BRDFKernels",
    "compute_reflectance",
    "KernelModelDeriver",
    "BRDFWhittakerDeriver",
    "PSFConvolver",
    "MonthlyBestPixelComposite",
    "MonthlyKernelWeightComposite",
    "MonthlyCompositeCollection",
    "build_monthly_best_pixel_composite",
    "build_monthly_best_pixel_kernel_composite",
    "MonthlyCompositeDatabase",
    "build_monthly_composite_database",
    "build_monthly_composites_from_brdf",
    "build_monthly_surface_prior_database",
    "generate_monthly_composites_from_brdf",
    "HyperspectralLibrary",
    "SpectralMappingConfig",
    "SpectralMapper",
    "convolve_hyperspectral_reflectance",
    "map_multispectral_reflectance",
    "needs_spectral_mapping",
    "query_surface_prior_from_monthly_database",
    "resample_geometry_for_surface_prior",
]
