from typing import Any

class RossThickLiSparse:
    def __init__(self, hb: float = ..., br: float = ...) -> None: ...
    def compute(self, vza: Any, sza: Any, raa: Any) -> Any: ...

class TwoLayerNN:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def predict(self, *args: Any, **kwargs: Any) -> Any: ...

class PSFConvolver:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def convolve(self, *args: Any, **kwargs: Any) -> Any: ...

def apply_laplacian(*args: Any, **kwargs: Any) -> Any: ...
def evaluate_grid_search_candidate_cost(*args: Any, **kwargs: Any) -> Any: ...
def evaluate_grid_search_cost_cube_with_provider(*args: Any, **kwargs: Any) -> Any: ...
def interpolate_to_fine_grid(*args: Any, **kwargs: Any) -> Any: ...
def quadratic_refine_grid_search(*args: Any, **kwargs: Any) -> Any: ...
def remap_to_coarse_grid(*args: Any, **kwargs: Any) -> Any: ...
def whittaker_smooth_cube(*args: Any, **kwargs: Any) -> Any: ...
